name: Event Handler

on:
  push:
    branches: [ main ]

jobs:
  emmit_event:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch event
        run: |
          curl -X POST https://api.github.com/repos/brijendra-beehyv/repo_dispatch/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
                  "event_type": "deploy-event",
                  "client_payload": {
                    "env": "staging"
                  }
                }'