name: Event Handler

on:
  repository_dispatch:
    types: [Event_XYZ]

jobs:
  XYZ:
    runs-on: ubuntu-latest

    steps:
      - name: Print Payload
        run: |
          echo {{ github.event.client_name.Param1 }}
          echo {{ github.event.client_name.Param2 }}
